### ISSUE TITLE
Seriously?! Uppercase Madness in a Repository? Not in a Million Years!

### ISSUE THREAD

**Issue by peseoane** [WorkPedroCampelo/APUNTES-2do-DAW#1]
Alright, I need to vent because it seems like some people still haven't grasped the message: uppercase letters in a repository are not just a bad idea, they're an abomination! I'm dead serious - how can anyone even think this is remotely acceptable?

First off, let me make it clear that I'm fed up with seeing repositories where every file name, folder, and even the README is typed in ALL CAPS. It's like someone is constantly yelling in my face while I browse through the code. No, thank you, I don't need to be yelled at; I already have enough stress in my life.

And spare me the excuse of "it's just a matter of preference." No, this goes beyond preference; this is about convention and readability. Conventions exist for a reason - to maintain a standard and make the code easily understandable for everyone. Uppercase letters break that convention and make everything harder to read.

Furthermore, think about the community. When we share code, we want others to quickly grasp it and contribute effectively. But if we're faced with a wall of uppercase, it's like trying to read a book in a language we don't understand. It's frustrating and inefficient.

And don't get me started on aesthetics. Do you seriously think an ALL CAPS README looks good? It's like composing an email in all uppercase. Aesthetically displeasing and utterly unacceptable.

In summary, using uppercase letters in a repository is a poor, anti-conventional choice, and it's just plain gross. If you truly want to be taken seriously in the development community, I strongly urge you to abandon this practice and respect the established conventions. For the sake of all of us!

And you know what's even worse than uppercase letters in a repository? Using uppercase in a filesystem! Are we in the 90s? Do we still think uppercase filenames are the pinnacle of innovation? Let's turn back time and bring back the good ol' floppy disks while we're at it.

I mean, seriously, who wakes up in the morning and thinks, "Ah yes, today is a great day to defy modern conventions and make everything scream at you in uppercase!" It's like trying to listen to music at full volume in a library - it's obnoxious, unnecessary, and makes people question your sanity.

Let me tell you, if you think naming your files in ALL CAPS is a good idea, you might as well go all the way and start coding in Wingdings. Because that's about as useful and intelligible as using uppercase for everything. Just a big, fat "NO" to that madness. Let's evolve, not devolve!

Oh, great! More uppercase absurdity in the commit messages. Seriously, who thought it was a fantastic idea to SHOUT in the commit history? It's like someone took Caps Lock, superglued it, and then lost the key to undo the mess.

And don't even get me started on the feeble reasons in commit b22d127a39dd. Weak? More like weaker than a kitten trying to bench press. It's like defending a crumbling sandcastle with toothpicks. A patch this bad is the epitome of coding sins, and slapping uppercase on it doesn't make it any better.

"This patch is ugly" - well, guess what? Typing everything in uppercase is uglier than a smashed pumpkin. It's not edgy; it's just edgily wrong. It's a guarantee for subtle locking issues? Oh, please, as if we needed more problems in the codebase. Congratulations, you've just added another layer of chaos.

So, Mel, do us all a favor: take a long, hard look in the mirror and ask yourself, "Do I really want to contribute to the deterioration of readability and sanity in this project?" Spoiler alert: The answer should be a resounding "HECK NO." This uppercase travesty is a monument to bad decisions and needs to be buried in a pit of regret.

Oh, joy! More of this infuriating mess with uppercase letters. It's astonishing how some people manage to take a simple problem like conflicts due to GCC headers and turn it into a raging dumpster fire of uppercase idiocy.

Let me break it down in words even someone who thinks uppercase is a good idea can understand: THIS. CODE. IS. AWFUL. The use of uppercase in this context is just mind-numbingly bad. It's like a sledgehammer to the face of readability.

Why, oh why, was this code written in such a moronic manner with uppercase everywhere? Two different conditionals like a bad comedy sketch, and to top it off, a shiny, new nonstandard function that's about as useful as a screen door on a submarine.

Can anyone provide a single valid reason why this abomination was coded in this ludicrous way, with uppercase ruling the roost? I'm all ears, although I suspect it's just another case of "I like uppercase, so I'll use it, damn the consequences."

And the audacity to claim it's for safety and security because it uses some fancy overflow detection functions? Please. It's like putting a band-aid on a severed limb. All this uppercase mess achieves is making the code a painful-to-read disaster.

I'm putting my foot down. This uppercase nightmare needs to be eradicated from the codebase. Whoever thought uppercase was the answer to anything here needs a reality check. It's not edgy or cool, it's just an eyesore. Let's clean up this mess and never allow this kind of abomination to plague our code again. Enough is enough!

**Let's make it crystal clear - we're not buying this excuse for brain damage. Whoever thought this was a good idea needs a reality check. Burn this mess, bury it, and let's never let such abomination stain our codebase again. Good riddance!**

**Comment by WorkPedroCampelo** [comment]
nono, its okay, no reopen

**Comment by peseoane** [comment]
Pues no
